ualbertalib/discovery

- Gemfile
- Gemfile.lock
Reverts ualbertalib/discovery#1160
The plot thickens.  It failed on both servers, with the same message on both, during "rake assets:precompile"... 
```
fatal: [forest]: FAILED! => {"changed": true, "cmd": "bundle exec rake assets:precompile", "delta": "0:00:01.934908", "end": "2018-05-22 11:26:49.521359", "failed": true, "rc": 1, "start": "2018-05-22 11:26:47.586451", "stderr": 
"DEPRECATION WARNING: The factory_girl gem is deprecated. Please upgrade to factory_bot. 
See https://github.com/thoughtbot/factory_bot/blob/v4.9.0/UPGRADE_FROM_FACTORY_GIRL.md for further instructions. 
(called from require at /usr/lib64/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:76)\n
rake aborted!\nLoadError: cannot load such file -- ci/reporter/rake/rspec\n/var/www/sites/blacklight/vendor/ruby/ …
```
> Revert "Temporary remove test gems to fix test build."

- app/controllers/catalog_controller.rb
Sean has OK'ed this change even though it does mean that databases cannot be filtered on language. We think that is better than having a duplicate facet.
> removing language facet duplication

- app/views/catalog/_show_tools.html.erb
The translation/i18n in blacklight in missing completed. Don't know why this one uses i18n string. This is not the right way to fix the issue, but it is the quickest way. And we will need to deal with i18n issue more holistically when/if we refactor the views.
> correct the capitalization for the view citation label - fixes #1058

- app/views/profiles/index.html.haml
Removing code which is slowing down the profile page. This code went and checked if a staff member's photo exists on www2 and if it doesn't exist displays a generic image. However, this process is slowing down the page load considerable. Therefor, I have removed it and instead added a thumbnail for all staff - generic ones for those without images.
> removing slow code on profile page

- .editorconfig
Noticed from last PR there was a bunch of space diffs among other things. Lets align our editors to be on the same page.
This brings in an EditorConfig which helps developers maintain consistent coding styles between different editors/IDEs.
More info and links to plugins (if your editor doesnt support editorconfig) here: https://editorconfig.org/
> Add editorconfig dot file so everyone has consistent coding styles

- Gemfile
- Gemfile.lock
- config/database.yml
- config/environments/development.rb
First step of many for doing the request forms:
Brings in this gem: https://github.com/ryanb/letter_opener
Email in development environment now opens a nice new tab displaying the email that was sent out:
Instead of hiding the contents of the email inside the console.
> Add letter opener gem to make testing emails easier

- docker-compose.lightweight.yml
- lib/docker/solr-precreate-discovery.sh
#1282 
Temporary fix to get this working without the pain of constantly having to take down and change docker configs to run discovery in both dev and test modes.
But we should maybe spend some time thinking about refactoring the docker stuff to be more in align with our other apps like jupiter (or if theres improvements/better ways to do this for jupiter codebase then by all means we can improve this as well)
> Bring over script to provision test/dev solr cores from jupiter to fix docker issue

- Gemfile
- Gemfile.lock
jbuilder and coffee-rails don't appear to be used.  Removing them!
We shouldn't be using therubyracer in production either... https://devcenter.heroku.com/articles/rails-asset-pipeline#therubyracer rails/rails#29285
closes #1375
> remove unused gems

- CHANGELOG.md
- README.md
- config/secrets.yml
From https://github.com/ualbertalib/di_internal/pull/38#issuecomment-437166354
> For now probably can just give a link to this section of the document: https://github.com/ualbertalib/di_internal/blob/master/System-Adminstration/UAT-Environment.md#access-discovery-uat-instance
> 
> Also just noticed we can probably turn off email intercepting on UAT now that we got mailcatcher (as mailcatcher does the intercepting)
> Remove uat mail intercept and documentation

- CHANGELOG.md
- config/application.rb
Previously was `VanillaBlacklight` which isn't accurate anymore (and horrible name to begin with?)
> Change application name to Discovery

- test/grabBag/t/libraryLocationsRegression.t
http://cardiff.library.ualberta.ca/job/discovery-grabBag/ identified that one library had disappeared with the latest re-index (count from 54 to 53). This change will make the message more descriptive and give a larger margin of error.
> give larger margin of error to flaky test

- .travis.yml
This will let us know that this project can be deployed against newer
versions of ruby. Currently 2.1.5 is used in production and we strongly
want to change this.
> tell travis to test newer versions of ruby

- CHANGELOG.md
- app/views/catalog/_show_header_default.html.erb
> Don't show conditions of use unless there is something to show

- app/services/symphony_service.rb
to ensure that the xml path exists before reasoning on it's contents
fixes #1377
> add a guard clause

- CHANGELOG.md
We did a [hotfix release](https://github.com/ualbertalib/discovery/releases/tag/3.0.96) for the conditions of use bug https://github.com/ualbertalib/discovery/commit/f56d63d2fadd77a81d3ff23a52934e6d970e93f8 at the request of @seanluyk 
Adding this hotfix release changelog to the master branch (the commit is already there).
> update changelog for v3.0.96

- CHANGELOG.md
- Gemfile
- Gemfile.lock
Upgrading Ruby to 2.5.x (#1506) is in progress but is still a couple weeks away.  When that's complete we should re-introduce this gem (#1506).
> remove erb-lint so that we can deploy expediently

- .dockerignore
- CHANGELOG.md
- Dockerfile
so that it is compatible with Ruby 2.1.5.
```
Step 7/22 : RUN bash -lc 'gem install bundler -v 1.17.3'
---> Running in 1b9994761f3f
mesg: ttyname failed: Inappropriate ioctl for device
Successfully installed bundler-1.17.3
1 gem installed
Removing intermediate container 1b9994761f3f
---> f2b9bfa78095
```
> pin version of bundler in Dockerfile

- CHANGELOG.md
- app/views/catalog/_show_default.html.erb
- app/views/catalog/show.html.erb
The range_limit XHR request is what gives the context to popluate the
range facet. While turbolinks helps to improve the perceived
performance, it prevents the XHR range_limit request from being loaded.
Links with Turbolinks disabled will be handled normally by the browser.
Also refactor links on show page to use rails helper link_to
#1290
> turn off turbolinks on the show page for range_limit

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- docker-compose.lightweight.yml
To address the issue noted here https://github.com/ualbertalib/discovery/pull/1520#issuecomment-471663175
This occurred because the version of blacklight_range_limit was bumped (with the negative consequences noted) https://github.com/ualbertalib/discovery/pull/1528/commits/381faff26a6550e40d1f363485ea566acf6610f7#diff-e79a60dc6b85309ae70a6ea8261eaf95R82
While I'm here, I'll also add a config change to the Solr docker in the lightweight config.
> Pin blacklight range limit

- CHANGELOG.md
- app/controllers/bookmarks_controller.rb
- app/views/bookmarks/_refworks.html.erb
- app/views/bookmarks/_tools.html.erb
- spec/features/bookmarks_spec.rb
- spec/fixtures/vcr_cassettes/item_to_bookmark.yml
Monkey patch BookmarksController#export_secret_token to use 
AS::KeyGenerator and set a 32 bit key
Also add some bookmark feature tests so that we can catch regressions of 
this feature.
Before:
```
ArgumentError: key must be 32 bytes
File "/var/www/sites/blacklight/vendor/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/message_encryptor.rb", line 79, in key=
File "/var/www/sites/blacklight/vendor/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/message_encryptor.rb", line 79, in _encrypt
File "/var/www/sites/blacklight/vendor/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/message_encryptor.rb", line 60, in encrypt_and_sign
File "/var/www/sites/blacklight/vendor/ruby/2.5.0/gems/blacklight-5.15.0/lib/blacklight/token_based_user.rb", line 40, in encrypt_user_id …
```
> Address key length issue with refworks/bookmarks after ruby upgrade

- CHANGELOG.md
Update the change log to prepare for the 3.0.106 release.
> update changelog for 3.0.106

- CHANGELOG.md
- test/grabBag/t/libraryLocationsRegression.t
Xpath of 'Library' on the advanced search page changed with bootstrap refactor.
Should resolve http://cardiff.library.ualberta.ca/job/discovery-grabBag/1473/console
> fix grabBag tests after bootstrap refactor

- CHANGELOG.md
- config/environments/production.rb
related to refworks export from bookmarks #1484 
potentially related to why analytics not being collected #1516
I imagine that this was missed when the cms/discovery moved domains.
> set default url as search.library.ualberta.ca in production

- CHANGELOG.md
The main purpose of this release is to fix the state of any related databases so that they use a consistent char set and collation.  This should workaround the problem experienced by the 3.0.110 release in staging.
> prepare for next release

- CHANGELOG.md
- Dockerfile
was finding that images built on docker hub and used on our architecture
would fail with illegal instrucation.  This workaround described
https://github.com/sass/sassc-ruby/issues/146#issuecomment-534197168
will make the prebuild gem portable.
#1796
> add bundler build config to make sassc gem portable

- CHANGELOG.md
- app/views/layouts/application.html.erb
- config/application.rb
It's hard to know which version of the code you're looking at.
If we can keep this up-to-date in our release management then we'll be
able to tell which version we see deployed by checking the page source.
fixes #1343
> Add version file and meta generator tag

- CHANGELOG.md
- app/helpers/holdings_helper.rb
#1824 Is a missed variable declaration in Location error handling
#1823 Is a typo where CirculationRules was called instead of CirculationRule
> Fix errors in Holdings Helper that are causing issues in the most recent deployment

- CHANGELOG.md
- config/application.rb
A release was cut without bumping the version number.
> bump version for 3.0.113

- CHANGELOG.md
- app/views/catalog/_index_default.html.erb
Searches that contain results with empty `location_tesim` were failing
since September 11, 2019 at ~9:30am.  There was a re-index shortly before
that date but not a direct correlation. The cause at this time and
any other implications is unknown.
location_tesim is used to show the item's copies owned by. It also is a
facet and used to detect if the UAL shield should be shown.
#1811
> use safe operator on empty location_tesim

- CHANGELOG.md
- app/helpers/holdings_helper.rb
It's taken more time that expected to resolve these and are triggering
many Rollbar Events ($$$).
#1853
> create an 'Unknown' entry for ActiveRecord::RecordNotFound events to limit Rollbar errors

- CHANGELOG.md
- test/grabBag/t/dataSanityRegression.t
In response to the UCP government budget for post-secondary universities
and how it was passed down to the library, we've implemented cuts to
our collections resulting in fewer databases. The tests should reflect this.
> change data sanity regression test values for databases

- CHANGELOG.md
- app/helpers/holdings_helper.rb
Was doing a database lookup for each holding of an item.  Where the item
has volumes upon volumes like catalog/1772030 this is very inefficient.
The solution incorporates memoization using `Hash.new` initializer to call a block only if the entry doesn't already
exist (https://www.justinweiss.com/articles/4-simple-memoization-patterns-in-ruby-and-one-gem/#and-what-about-parameters?)
I was worried that instance variables (@Locations) would have a cache invalidation
problem, but found out that there is a seperate controller instance for
each web request so this isn't really an issue.
> use memoization to protect against N+1 query

- README.md
> Update README with symphony_nightly task

- CHANGELOG.md
- config/application.rb
I chose a minor release because of the added symphony_nightly generator. Probably should have triggered this earlier with some previous changes.
This is a local branch now rather than from my fork so that travis will be okay with our danger key.
> bump for 3.1.0 release

- CHANGELOG.md
- app/helpers/holdings_helper.rb
When I added memoization to protect against an N+1 query I left the e Error variable behind.
Related to https://github.com/ualbertalib/discovery/commit/ee295932dfd58c7275b68e6d0b5052215c09d115
> remove calls to error codes

- CHANGELOG.md
- lib/generators/symphony_nightly/symphony_nightly_generator.rb
In a recent email @nmacgreg was concerned about how this should handle exceptions.  I wrote, 
> First, something (cron) or someone must invoke `rails g[enerate] symphony_nightly` (where the 'enerate' is optional). This reads the two files in the data directory and creates a database migration with the timestamp of today's date. That's it, that's all that task does.  If the file/files don't exist it will terminate in error (No such file or directory @ rb_sysopen - data/data4discovery.txt (Errno::ENOENT)) and create an empty migration file (in db/migrate). It will not check if the file has changed from any previous state or inspect a timestamp. If you try to run the same generator on the same calendar day it will fail with the message:
conflict …
> abort `symphony_nightly` if data files do not exist.

- CHANGELOG.md
- db/migrate/20200319205106_add_symphony_id_to_location.rb
- db/schema.rb
- lib/generators/solr_marc_prep/USAGE
- lib/generators/solr_marc_prep/solr_marc_prep_generator.rb
- lib/generators/solr_marc_prep/templates/institution.bsh.erb
- lib/generators/solr_marc_prep/templates/location_facet.bsh.erb
- lib/generators/symphony_nightly/templates/update_symphony_nightly.erb
- lib/tasks/ingest.rake
- spec/lib/generators/solr_marc_prep/solr_marc_prep_generator_test.rb
Since release 3.0.113, we have moved the management of location codes,
circulation rules, statuses, and item types into DB, instead of static
yml file in Discovery. This will avoid a new release every time a change
is introduced in Symphony, and will allow for more efficient/accurate
data used in Discovery.
Now we need to use this same information when indexing/ingesting the
MARC data into Solr. When `rake ingest[collection]` is invoked, the
generator will be called which will use the current database values in
a template to replace two files that map to human readable strings for
Institution and Library in the application's facets.
#1939
> add solr_marc_prep generator consumed by the ingest rake task

- CHANGELOG.md
- test/grabBag/t/libraryLocationsRegression.t
The reskin simplified the layout and the path to the list of libraries on the advanced search changed.
This makes the test a little bit more robust by matching relative to the form  element
> fix regression test after reskin

- CHANGELOG.md
- app/controllers/catalog_controller.rb
Our initial understanding of HathiTrust's ETAS programme was that when we restored access to the print collection we would have to remove the HathiTrust ETAS links (i.e. ETAS is only allowed when there is no access to the print collection). Clarification from HathiTrust indicates that access to the print collection can be restored as long as ETAS items are not accessible.
We're going to suppress the hold button in Discovery whenever the record is in the overlap table, without regard for whether or not the item is actually still available via the HathiTrust API, and knowing that the overlap report is not currently being refreshed in a timely manner.
To be clear: this means that we 100% expect that there will be corner cases in which the hold button will be unavailable but no access in …
> discourage holds placed on items with HathiTrust access

- CHANGELOG.md
- Dockerfile
When we bumped the version of bundler in Gemfile.lock this started the builds on Docker hub failing. Updating
rubygems and installing the correct version of bundler should resolve this issue.
Install the correct version of bundler in our Dockerfile.
> update bundler version in Docker for uat

- CHANGELOG.md
- config/application.rb
Prepare for 3.4.0 release with hold button suppressed for items in Hathi Trust report.
> bump CHANGELOG and VERSION for 3.4.0 release 

- CHANGELOG.md
- app/views/catalog/_facet_pagination.html.erb
Turns out this is a known problem and fixed in a 6.x version of Blacklight.  We don't have the interest to bump our blacklight version so patching instead.  Thanks @orangewolf for finding the solution!
Related to #2011
> remove span tag showing in facets

- CHANGELOG.md
- app/models/rcrf_special_request.rb
- config/locales/en.yml
Library operations have been modified for public health reasons related to the Covid-19 pandemic.  Bruce Peel Special Collections remains closed with limited services available and RCRF requests are only available for pickup at Rutherford. 
Related to #2038 and #2039
Updated the text for the BPSC form and changed the libraries available in the selection list for RCRF per email request and OTRS ticket.
> Request Form updates

- CHANGELOG.md
- config/application.rb
- config/locales/en.yml
There was just a minor change requested to a previous change on the BPSC request form.  The text change was missing the prompt https://github.com/ualbertalib/discovery/issues/2037#issuecomment-675047778
Related to #2037 
Edit the text for the form.  Bump for a new release.
> Restored the prompt from a previous change to the BPSC request form

- CHANGELOG.md
- Dockerfile
- Gemfile.lock
We're not going to get upstream updates for Rails 4.2 and we've pinned blacklight so we've made the changes there and now we need to use them in discovery.
It looks like bundler 2.x is not compatible with Rails 4.2.  I'm not sure what combination of things gave me the impression that we could do the bump before.
Related to CVE-2020-15169 and https://github.com/ualbertalib/blacklight/pull/5
Revert bundler to 1.17.3 and bump blacklight
> Default translation

- CHANGELOG.md
- config/SolrMarc/symphony_index.properties
Concordia library uses WorldCat Local, and OCLC does not index our 001 cataloguing key. This means, they can't link directly to an item for hold-placing purposes. They can use the OCLC number, which is indexed in WorldCat Local, but we currently don't index that field. If we index that field, we may be able to come up with a solution for them to build a working place hold link.
Related to #2050 https://github.com/ualbertalib/blacklight_solr_conf/pull/8
index `035a` as `oclc_number_t`
> added oclc number to symphony indexing

- CHANGELOG.md
- config/initializers/cve-2020-8161.rb
A directory traversal vulnerability exists in rack < 2.2.0 that allows an attacker perform directory traversal vulnerability in the Rack::Directory app that is bundled with Rack which could result in information disclosure.
We don't appear to use Rack::Directory in the application but monkey patching will ensure we're covered.
monkey patch Rack::Directory#list_directory like https://groups.google.com/forum/#!topic/rubyonrails-security/IOO1vNZTzPA says but adapted for Rack 1.6-stable https://github.com/rack/rack/blob/47a1fd73fc77f094573f4215b0fc884f4ac1c03c/lib/rack/directory.rb#L79-L105
> monkey patch rake CVE-2020-8181

- CHANGELOG.md
- config/environments/uat.rb
- docker-compose.yml
Distinct server names or routes to applications instead of port ‘x’ is Jupiter, port ‘y’ is avalon, etc. Personally, I find names easier to remember than numbers. If the applications are containerised, a reverse proxy could handle the routing.
nginx-proxy is doing the routing for us.
Related to https://github.com/ualbertalib/jupiter/issues/1724
docker-compose.yml with environment variables that nginx-proxy is expecting.  Changed the default_url to reflect the discovery subdomain.
> discovery.uat.library.ualberta.ca

- CHANGELOG.md
- config/ingest.yml
- lib/tasks/ingest.rake
- spec/fixtures/database_test_set.xml
Ocassionally we'll get a response from https://sfx-resolver.hosted.exlibrisgroup.com/resolver/cgi/public/get_file.cgi?file=sfxdata.xml that isn't utf-8 encoded and it ends up clearing out all our e-journals. Backing up the existing file and exiting if the new file isn't parsable should give us some more warning.
Also noticed some errors in the database_test_set so fixed that too.
Related to #1875 
Fixed database_test_set and added circuit breaker for sfx ingest.
> circuit breaker to SFX ingest

- .travis.yml
- CHANGELOG.md
- README.md
- config/application.rb
- lib/tasks/ingest.rake
`rake ingest[sfx]` after adding the circuit breaker caused the ingest script to run out of memory:
```
rake aborted!
Errno::ENOMEM: Cannot allocate memory - java
```
> Kilmarnock in Prod  has 4Gb memory / 2Gb swap and performs this feat monthly without complaint.
Forest has the same virtual h/w, but was throwing off Netdata alarms about memory & swap usage while ingesting SFX specifically
Basically we read the file twice with two different GC'd languages, thus the file's in memory twice.  oops
Related to #1875 
Outsource the validation check to [xmllint](http://xmlsoft.org/xmllint.html) using Ruby library [Open3](https://devdocs.io/ruby~2.6/open3).
> Circuit breaker memory

- CHANGELOG.md
- config/application.rb
- lib/tasks/ingest.rake
After the last "fix" the large file continued to have issues.  Found the --stream flag for xmllint and it seems to have solved the mystery.
From `man xmllint`
```
--stream
Use streaming API - useful when used in combination with --relaxng or --valid options for validation of files that are too large to be held in memory.
```
Related to #1875
use `--stream` flag when invoking `xmllint` on large sfx ingest files.
> fix memory use and bump for release

- .github/PULL_REQUEST_TEMPLATE
- spec/features/catalog_search_spec.rb
- spec/features/item_holding_table_spec.rb
- spec/features/item_ill_link_spec.rb
```
Failure/Error: visit
Net::ReadTimeout:
Net::ReadTimeout
```
The only change I could see between working and non working runs was the solr docker container and google chrome 86.
Related to https://travis-ci.org/github/ualbertalib/discovery/builds/732915914
Skip the failing tests in the CI environment.  Also added a reminder to run tests in PR template.
> skip these tests only on travis CI

- spec/features/catalog_search_spec.rb
- spec/features/item_holding_table_spec.rb
- spec/features/item_ill_link_spec.rb
- spec/fixtures/vcr_cassettes/item_ill_link.yml
- spec/fixtures/vcr_cassettes/item_sfx_holding_table.yml
- spec/fixtures/vcr_cassettes/sfx_result.yml
Three tests were giving a timeout error, something to do with VCR I assume. Regenerated the cassettes and that seems to have fixed the issue.
```
Failed examples:
rspec ./spec/features/catalog_search_spec.rb:20 # Catalog Search User visits an SFX item result
rspec ./spec/features/item_holding_table_spec.rb:19 # Item has proper holding table Sfx item has proper holding table
rspec ./spec/features/item_ill_link_spec.rb:2 # Link to ill Sfx item has link to ill
3:20 PM
Failures:
1) Catalog Search User visits an SFX item result
Failure/Error: visit 'catalog/954921333008'
Net::ReadTimeout:
Net::ReadTimeout
2) Item has proper holding table Sfx item has proper holding table
Failure/Error: visit '/catalog/954921333007'
Net::ReadTimeout:
Net::ReadTimeout
3) Link to ill Sfx item has link to ill …
```
> fix failing tests caused by VCR

- Dockerfile
Docker web container needs xmllint installed
Related to #2067 
Install prerequisite.
> add xmllint to docker container

- CHANGELOG.md
- config/application.rb
- docker-compose.lightweight.yml
- lib/generators/symphony_nightly/templates/update_symphony_nightly.erb
We're trying to automate data flowing from Symphony configuration files to Discovery to provide user better labels in the holdings table.
When we tried the two steps (`rails g symphony_nightly` `rake db:migrate`) in staging/production we encountered a failure in the migration and complains about foreign key constraints.  There was a bug in the migration template that was hidden in development/test because a different, more tolerant version of MySQL was being used (5.7 vs 5.5 in production)
Related to #2142 
- fixed symphony_nightly migration foreign key error 
- bump version for new release
> Symphony nightly migration foreign key error
