ualbertalib/discovery

- app/controllers/ebooks_controller.rb
The ebook controller wasn't performing the correct query for ebooks. Fixed now.
> Fix Ebooks controller. Closes #254.

- app/helpers/holdings_helper.rb
- app/services/sfx_service.rb
- config/application.rb
- spec/unit/sfx_service_spec.rb
also included configurable timeout value which requires app restart.
> add error handling so that sfx outage will fail gracefully fixes #666

- app/controllers/catalog_controller.rb
- lib/ingest/database_om.rb
- lib/ingest/databases.rb
Added language facet to databases
> Fixing Issue #922

- app/helpers/blacklight/results_records.rb
- app/views/articles/_facets.html.erb
- app/views/articles/_results_pagination.html.erb
- app/views/articles/_search_results.html.erb
- app/views/catalog/_main_url_display.html.erb
> fixing issue: Usability issue with articles list view #994

- app/assets/stylesheets/ualib-custom.scss
- app/assets/stylesheets/ualib-discovery.scss
- app/views/advanced/_facet_limit.html.erb
Issue #989 has been fixed as requested
> fixing issue #989: UI tweaks

- app/assets/stylesheets/ualib-custom.scss
Fixing font and padding issues
> Fixing font issues

- app/controllers/profiles_controller.rb
- config/secrets.yml
(Re: my CR684)
I've moved the credentials for editing Profiles, into secrets.yml. 
Please review!
> Profiles password

- config/library_codes.yml
I removed the *[In Transition]* notes from two locations added last year.
> Closes #1127.

- Gemfile.lock
resolves issue with ruby 2.1.5 build created here: https://github.com/ualbertalib/discovery/commit/bacfd27191ee1b2de150e698af384d6e0524b4b6#diff-e79a60dc6b85309ae70a6ea8261eaf95
> ruby 2.1.5 compatible Gemfile.lock

- README.md
- app/views/layouts/french.html.erb
- app/views/layouts/home.html.erb
- app/views/shared/_header_navbar.html.erb
- app/views/shared/_header_navbar_french.html.erb
- test/grabBag/t/dataSanityRegression.t
- test/grabBag/t/randomIndex.t
Integration test run by Jenkins CI are ignored because they've come into disrepair.  I've updated the tests or the code where I think appropriate. Also added readme for how to run.
> update the integration tests

- Gemfile
- Gemfile.lock
Addresses potential security vulnerabilities in your dependencies.
#1164
> WIP - upgrade nokogiri and paperclip

- app/controllers/symphony_controller.rb
- config/locations.yml
adding ejournals and databases into main search (for the bento removal). Fixing library codes in locations.yml
> Some last minute fixes

- config/SolrMarc/index_scripts/location_facet.bsh
> fix unexpected underscores and dashes in location codes

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
@seanluyk 
As discussed before, I've added the issue templates (the one used in Jupiter) for your review. Please feel free to comment/suggest changes to the templates. Or if more are needed. 
Weiwei
> added issue templates for discovery project

- app/views/catalog/_show_tools.html.erb
Hey @weiweishi, tried to throw a quick PR for this together. 
However I couldn't get my local discovery to get up and running for some reason (issue with solr...think docker image is broken? It's only creates the test core, not the development core :thinking:) . So wasn't actually able to test this. 
But this _should_ work or at least give you an ideal of whats needed.
Also not sure if natasha is working on this? She assigned herself to this and put the ticket in progress?
These catalog views folder needs a heavy refactor....we shouldn't have 70 views and partials for this! :astonished: https://github.com/ualbertalib/discovery/tree/master/app/views/catalog. Majority of these are 1-3 line partials that are never used more than once :disappointed:
> Add link for librarian view - fix#1242

- CHANGELOG.md
Hi Sean
We've added the librarian view to the tool side bar as indicated in PR #1277, and fix #1058. If you are okay with these changes, please approve this change to the changelog, and we will tag the new release to start testing on Monday. 
Weiwei
> update changelog for #1242 and #1058 change

- config/environments/development.rb
- config/environments/production.rb
- config/environments/staging.rb
- config/environments/test.rb
> set default url options in different environments

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/initializers/rollbar.rb
- config/secrets.yml
Need to set or replace `rollbar_token: <%= ENV['ROLLBAR_TOKEN'] %>` in secrets.yml with `post_server_item` at https://rollbar.com/ualbertalib/discovery/settings/access_tokens/
> rollbar setup

- CHANGELOG.md
> changelog for release 3.0.88

- app/controllers/application_controller.rb
- test/grabBag/t/regressionStringsSolr.t
* 8080 port was required
* add method for rails app to pick up default_url_options
> fix grab bag tests

- CHANGELOG.md
- Gemfile
- Gemfile.lock
> rollback blacklight gem to protect SMS and Email features.

- CHANGELOG.md
> changelog for release 3.0.90

- .rubocop.yml
- config/initializers/intercept_mail.rb
- config/locales/en.yml
- config/secrets.yml
- lib/discovery/email_interceptor.rb
Preliminary work for request forms.
> Email interceptor to prevent staging/uat environments to send real email out

- app/controllers/application_controller.rb
- app/controllers/blacklight_advanced_search/advanced_controller.rb
- app/controllers/catalog_controller.rb
- app/helpers/blacklight/facets_helper_behavior.rb
- app/helpers/holdings_helper.rb
- app/views/catalog/_symphony_holdings.html.erb
- config/initializers/lookup_tables.rb
- config/initializers/symphony_lookup_tables.rb
- config/locales/en.yml
- spec/helpers/holdings_helper_spec.rb
closes #1247
depends on #1184 and #1260 
TODO:
> request me button to link to readonsite forms

- README.md
- Otherwise Ingest scripts won't work and as a result tests will fail ( as tests want solr to be ingested with 1000s of records and require ingested data before running?)
> Update README.md to make mention about requiring java install

- CHANGELOG.md
Added new changelog entries for past PRs that have been added in last 2-3 weeks.
> Add new changelog entries for past work

- CHANGELOG.md
- app/views/catalog/_symphony_holdings.html.erb
Comment out the Read on Site feature until the forms are finished. Also added some missed changelog entries.
> comment out partially implemented feature and changelog

- config/SolrMarc/index_scripts/location_facet.bsh
- config/locations.yml
https://github.com/ualbertalib/NEOSDiscovery/pull/208#discussion_r231326868
> correct Kings University

- config/SolrMarc/index_scripts/location_facet.bsh
- config/locations.yml
Provided by Andrea Dupuis via email.
Also confirmed that Rockyview General Hospital and Kaye Edmonton Clinic are present.
> corrections to AHS locations

- app/views/catalog/_symphony_holdings.html.erb
> sometimes the reserve rule isn't present

- config/locales/blacklight.en.yml
> change application name to change open search description

- app/mailers/request_form_mailer.rb
> Changed who RCRF read on site request form emails

- CHANGELOG.md
- app/controllers/bpsc_read_on_site_requests_controller.rb
- app/helpers/holdings_helper.rb
- app/models/bpsc_read_on_site_request.rb
- app/views/bpsc_read_on_site_requests/new.html.erb
- app/views/catalog/_symphony_holdings.html.erb
- app/views/request_form_mailer/bpsc_read_on_site_request.html.erb
- app/views/request_form_mailer/bpsc_read_on_site_request.text.erb
- config/locales/en.yml
- spec/controllers/bpsc_read_on_site_requests_controller_spec.rb
- spec/helpers/holdings_helper_spec.rb
- spec/models/bpsc_read_on_site_request_spec.rb
#1404: Adds call number to request form for BPSC On Site.
Made the assumption that this is a required field?
> #1404: Add call number to BPSC On Site Form

- app/views/catalog/_show_default.html.erb
> sanitize notes in contents field

- CHANGELOG.md
Missed this in my last PR.  I need to do this first rather than last so I don't forget.
> sanitize notes in contents field changelog

- app/mailers/request_form_mailer.rb
https://github.com/ualbertalib/discovery/issues/1184#issuecomment-446747015
> Add new email address for BPSC Request Form

- Dockerfile
`rake assets:precompile` in the Dockerfile was changing the owner of logs and tmp.  Same as https://github.com/phusion/passenger-docker/issues/143#issuecomment-234171238
> solve permissions issue on log and tmp directory

- CHANGELOG.md
- app/helpers/catalog_helper.rb
- spec/helpers/catalog_helper_spec.rb
Add tests to catch regressions and rename the boolean test to be more 
meaningful and to miror the method name.
#1454
> fix logic for when to add proxy to database url

- CHANGELOG.md
- app/controllers/catalog_controller.rb
- app/models/solr_document.rb
- app/views/catalog/_index_header_default.html.erb
#1480 added a bunch of subfields to what is indexed for title, including 
subtitles. So this isn't necessary.
> remove subtitle from display

- .rubocop.yml
- .rubocop_todo.yml
- .travis.yml
- Gemfile
- Gemfile.lock
- README.md
- app/controllers/catalog_controller.rb
- app/helpers/blacklight/facets_helper_behavior.rb
- app/models/solr_document.rb
- app/services/symphony_service.rb
- app/views/catalog/_facet_layout.html.erb
- app/views/catalog/_index_header_default.html.erb
- app/views/catalog/index.atom.builder
- app/views/layouts/application.html.erb
- spec/lib/tasks/ingest_rake_spec.rb
- remove old ruby dependency
- fixed rubocop nags
- unlock and update rubygems
- reintroduce erblint and fix nags
- address some deprecation warnings.
#1432
> update ruby 2.5.3

- CHANGELOG.md
- config/locales/en.yml
#1500 
If we're ready I can remove the feature flag per #1515 if desired as part of this too.
> minor change to the preamble text in the form from BPSC staff

- CHANGELOG.md
- app/views/catalog/_holdings.html.erb
> remove feature flag from BPSC form

- spec/features/catalog_search_spec.rb
- spec/fixtures/vcr_cassettes/sfx_result.yml
Trying to fill out the tests for different cases.  Also illustrates what a SFX response looks like in VCR cassette.
> test for an item with SFX lookup

- CHANGELOG.md
- app/views/catalog/_holdings.html.erb
> remove feature flag for RCRF Read on Site and Micro/Newspaper forms

- CHANGELOG.md
- Dangerfile
- fixed error by using two different statements
#1602
> Error in Dangerfile

- CHANGELOG.md
- spec/features/catalog_search_spec.rb
- spec/features/search_faceting_spec.rb
- Added tests for all facets
- Added test for clicking more to view all facets
- Added tests for using more facet modal
#1622
> Add feature tests for search faceting

- CHANGELOG.md
- spec/features/search_results_per_page_spec.rb
- Added feature tests for setting search results per page to 25, 50, and 100
#1630
> Add feature tests for search results per page

- CHANGELOG.md
- app/views/catalog/_holdings.html.erb
- app/views/catalog/_show_sidebar.html.erb
- app/views/catalog/sms.html.erb
- config/locales/en.yml
- Made email language consistent
- Made text language consistent
- Made request language consistent
#1607
> Make export and request language consistent

- CHANGELOG.md
- updated the version on the changelog
> Update changelog for 3.0.107

- CHANGELOG.md
- app/assets/stylesheets/ualib-custom.scss
- app/controllers/bpsc_read_on_site_requests_controller.rb
- app/controllers/rcrf_read_on_site_requests_controller.rb
- app/controllers/rcrf_special_requests_controller.rb
- app/models/bpsc_read_on_site_request.rb
- app/models/rcrf_read_on_site_request.rb
- app/models/rcrf_special_request.rb
- app/views/bpsc_read_on_site_requests/new.html.erb
- app/views/catalog/_holdings.html.erb
- app/views/rcrf_read_on_site_requests/new.html.erb
- app/views/rcrf_special_requests/new.html.erb
- Made request form not open in new tab
- Made forms redirect to the referring item page
- Fixed BPSC form from displaying mid-screen
- Added required field to view as needed for better validation
#1443
> BPSC and RCRF form submission completion redirection behaviour

- CHANGELOG.md
- spec/features/search_results_have_proper_metadata.rb
- Added tests to ensure that search results for a journal contain proper metadata
#1704
> Journal records contain proper metadata

- CHANGELOG.md
- spec/features/item_holding_table_spec.rb
- spec/fixtures/vcr_cassettes/item_kule_holding_table.yml
- spec/fixtures/vcr_cassettes/item_requestable_holding_table.yml
- spec/fixtures/vcr_cassettes/item_sfx_holding_table.yml
- spec/fixtures/vcr_cassettes/item_symphony_holding_table.yml
- Checked holding table for symphony, sfx, kule, and requestable items
#1712
> Ensure that holding table for various items has proper content

- CHANGELOG.md
- spec/features/item_author_links_spec.rb
- spec/fixtures/vcr_cassettes/item_author_links.yml
- Ensured that an item has a useable author link
#1710
> Feature tests for item author links

- CHANGELOG.md
- spec/features/item_chained_subject_linking_spec.rb
- spec/fixtures/vcr_cassettes/item_chained_subject_linking.yml
- Ensured that subject chains are present
- Ensured that subject chain links search by full subject properly
- Ensured that searching by subject chain brings up proper result
#1708
> Feature tests for chained subject linking

- .travis.yml
- CHANGELOG.md
- app/views/bpsc_read_on_site_requests/new.html.erb
- config/locales/en.yml
- Added closure disclosure to form field
#1728
> Add additional text for BPSC request form

- CHANGELOG.md
Update the changelog for release 3.0.109.
> updated Changelog.md for 3.0.109 release

- CHANGELOG.md
Changelog prepared for new release 3.0.110.
> updated changelog for 3.0.110

- CHANGELOG.md
- app/views/catalog/_place_hold.html.erb
adding italics around "Place hold with barcode and PIN" - requested by WAT to increase visibility for alumni borrowers.
> adding italics

- CHANGELOG.md
- config/application.rb
Prepare for new release 3.0.114.
> Update version and changelog for 3.0.114

- CHANGELOG.md
- config/SolrMarc/index_scripts/location_facet.bsh
We are working on a way to automatically update these values which come from
Symphony [https://github.com/ualbertalib/discovery/issues/1843] but until
that is completed we need to continue to update in multiple places :(
#1811
> concordin to location facet mapping for use at index time

- Gemfile
Edit: Left this blank, to see if DangerBot warns me. It did! 
Similar to https://github.com/ualbertalib/jupiter/pull/1421 for Jupiter
> #1885 Danger gem should be in test group and required false

- CHANGELOG.md
- app/views/catalog/_holdings.html.erb
- spec/features/item_ill_link_spec.rb
> Add new Conditions of Use link to SFX e-journal records.

- CHANGELOG.md
Updated the changelog with the new release number.
> Update Changelog for the release

- CHANGELOG.md
- config/locales/en.yml
as requested by BPSC staff.
#1889
> Changed hours and wording of question for BPSC request form

- CHANGELOG.md
- config/application.rb
> bump for 3.2.0 release

- CHANGELOG.md
- app/assets/javascripts/ualib-discovery.js
> Fix hathitrust mixed content blocking

- CHANGELOG.md
- config/application.rb
> Bump for 3.2.1 release

- CHANGELOG.md
- config/application.rb
Bump to bundler (2.1.4)
New header and footer and css changes.
> bump CHANGELOG and VERSION for 3.3.0 release

- CHANGELOG.md
- config/application.rb
Prepare for 3.5.0 release with updates for request me forms.
> bump CHANGELOG and VERSION for 3.5.0 release

- CHANGELOG.md
- config/application.rb
> bump CHANGELOG and VERSION for 3.5.5 release

- CHANGELOG.md
- config/application.rb
> bump CHANGELOG and VERSION for 3.5.6 release

- CHANGELOG.md
- config/application.rb
> bump CHANGELOG and VERSION for 3.5.9 release
